# Author: Aarav Shah
# Portfolio: aaravshah1311.is-great.net
# github: github.com/aaravshah1311

blank_issues_enabled: true
contact_links:
  - name: 📖 Documentation
    url: https://github.com/Agent-2/wiki
    about: Check our documentation for answers
  - name: 💬 Discussions
    url: https://github.com/Agent-2/discussions
    about: Ask questions and share ideas
